Traceback (most recent call last):
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/manage.py", line 21, in <module>
    main()
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/venv/lib/python3.9/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/venv/lib/python3.9/site-packages/django/core/management/base.py", line 322, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/venv/lib/python3.9/site-packages/django/core/management/base.py", line 296, in create_parser
    self.add_arguments(parser)
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/venv/lib/python3.9/site-packages/django/core/management/commands/test.py", line 44, in add_arguments
    test_runner_class = get_runner(settings, self.test_runner)
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/venv/lib/python3.9/site-packages/django/test/utils.py", line 302, in get_runner
    test_runner_class = test_runner_class or settings.TEST_RUNNER
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/bruno/Área de Trabalho/kenzie/q4/entregas/4_ekommerce/ekommerce/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 189, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
